ConnectionBDBundle\Entity\DienteMatriz:
    type: entity
    table: diente_matriz
    indexes:
        diente_diente_matriz_idx:
            columns:
                - idDiente
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cara:
            type: integer
            nullable: false
            unsigned: false
        posicion:
            type: integer
            nullable: false
            unsigned: false
        color:
            type: integer
            nullable: false
            unsigned: false
    manyToOne:
        iddiente:
            targetEntity: Diente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idDiente:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
