ConnectionBDBundle\Entity\Odontologo:
    type: entity
    table: odontologo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
        telefono:
            type: string
            nullable: false
            length: 15
            fixed: false
        correoElectronico:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: correo_electronico
        practicante:
            type: boolean
            nullable: true
        cedula:
            type: string
            nullable: false
            length: 45
            fixed: false
    lifecycleCallbacks: {  }
