ConnectionBDBundle\Entity\Paciente:
    type: entity
    table: paciente
    indexes:
        odontologo_paciente_idx:
            columns:
                - idOdontologo
        encargado_paciente_idx:
            columns:
                - idEncargado
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cedula:
            type: string
            nullable: false
            length: 45
            fixed: false
        fechaDeIngreso:
            type: date
            nullable: false
            column: fecha_de_ingreso
        sexo:
            type: integer
            nullable: false
            unsigned: false
        edad:
            type: integer
            nullable: false
            unsigned: false
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
        ocupacion:
            type: string
            nullable: true
            length: 45
            fixed: false
        carne:
            type: string
            nullable: true
            length: 7
            fixed: false
        apartadoPostal:
            type: integer
            nullable: true
            unsigned: false
            column: apartado_postal
        beca:
            type: integer
            nullable: true
            unsigned: false
        carrera:
            type: string
            nullable: true
            length: 45
            fixed: false
        estadoCivil:
            type: integer
            nullable: true
            unsigned: false
            column: estado_civil
        direccion:
            type: string
            nullable: false
            length: 100
            fixed: false
        telefonoHabitacion:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: telefono_habitacion
        telefonoTrabajo:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: telefono_trabajo
        telefonoMovil:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: telefono_movil
        correoElectronico:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: correo_electronico
        sintoma:
            type: string
            nullable: true
            length: 100
            fixed: false
    manyToOne:
        idencargado:
            targetEntity: Encargado
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idEncargado:
                    referencedColumnName: id
            orphanRemoval: false
        idodontologo:
            targetEntity: Odontologo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idOdontologo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
