ConnectionBDBundle\Entity\Usuarios:
    type: entity
    table: usuarios
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        user:
            type: string
            nullable: false
            length: 20
            fixed: false
        password:
            type: string
            nullable: false
            length: 25
            fixed: false
    lifecycleCallbacks: {  }
