<?php

namespace Proxies\__CG__\ConnectionBDBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paciente extends \ConnectionBDBundle\Entity\Paciente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'id', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'cedula', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'fechaDeIngreso', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'sexo', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'edad', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'nombre', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'ocupacion', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'carne', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'apartadoPostal', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'beca', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'carrera', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'estadoCivil', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'direccion', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'telefonoHabitacion', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'telefonoTrabajo', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'telefonoMovil', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'correoElectronico', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'sintoma', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'idencargado', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'idodontologo');
        }

        return array('__isInitialized__', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'id', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'cedula', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'fechaDeIngreso', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'sexo', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'edad', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'nombre', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'ocupacion', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'carne', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'apartadoPostal', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'beca', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'carrera', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'estadoCivil', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'direccion', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'telefonoHabitacion', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'telefonoTrabajo', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'telefonoMovil', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'correoElectronico', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'sintoma', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'idencargado', '' . "\0" . 'ConnectionBDBundle\\Entity\\Paciente' . "\0" . 'idodontologo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Paciente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCedula($cedula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedula', array($cedula));

        return parent::setCedula($cedula);
    }

    /**
     * {@inheritDoc}
     */
    public function getCedula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedula', array());

        return parent::getCedula();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaDeIngreso($fechaDeIngreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaDeIngreso', array($fechaDeIngreso));

        return parent::setFechaDeIngreso($fechaDeIngreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaDeIngreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaDeIngreso', array());

        return parent::getFechaDeIngreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', array($sexo));

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', array());

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdad($edad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdad', array($edad));

        return parent::setEdad($edad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdad', array());

        return parent::getEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setOcupacion($ocupacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOcupacion', array($ocupacion));

        return parent::setOcupacion($ocupacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getOcupacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOcupacion', array());

        return parent::getOcupacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarne($carne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarne', array($carne));

        return parent::setCarne($carne);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarne', array());

        return parent::getCarne();
    }

    /**
     * {@inheritDoc}
     */
    public function setApartadoPostal($apartadoPostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApartadoPostal', array($apartadoPostal));

        return parent::setApartadoPostal($apartadoPostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getApartadoPostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApartadoPostal', array());

        return parent::getApartadoPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeca($beca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeca', array($beca));

        return parent::setBeca($beca);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeca', array());

        return parent::getBeca();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarrera($carrera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarrera', array($carrera));

        return parent::setCarrera($carrera);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarrera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarrera', array());

        return parent::getCarrera();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoCivil($estadoCivil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoCivil', array($estadoCivil));

        return parent::setEstadoCivil($estadoCivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoCivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoCivil', array());

        return parent::getEstadoCivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoHabitacion($telefonoHabitacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoHabitacion', array($telefonoHabitacion));

        return parent::setTelefonoHabitacion($telefonoHabitacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoHabitacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoHabitacion', array());

        return parent::getTelefonoHabitacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoTrabajo($telefonoTrabajo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoTrabajo', array($telefonoTrabajo));

        return parent::setTelefonoTrabajo($telefonoTrabajo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoTrabajo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoTrabajo', array());

        return parent::getTelefonoTrabajo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoMovil($telefonoMovil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoMovil', array($telefonoMovil));

        return parent::setTelefonoMovil($telefonoMovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoMovil', array());

        return parent::getTelefonoMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreoElectronico($correoElectronico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreoElectronico', array($correoElectronico));

        return parent::setCorreoElectronico($correoElectronico);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreoElectronico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreoElectronico', array());

        return parent::getCorreoElectronico();
    }

    /**
     * {@inheritDoc}
     */
    public function setSintoma($sintoma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSintoma', array($sintoma));

        return parent::setSintoma($sintoma);
    }

    /**
     * {@inheritDoc}
     */
    public function getSintoma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSintoma', array());

        return parent::getSintoma();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdencargado(\ConnectionBDBundle\Entity\Encargado $idencargado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdencargado', array($idencargado));

        return parent::setIdencargado($idencargado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdencargado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdencargado', array());

        return parent::getIdencargado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdodontologo(\ConnectionBDBundle\Entity\Odontologo $idodontologo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdodontologo', array($idodontologo));

        return parent::setIdodontologo($idodontologo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdodontologo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdodontologo', array());

        return parent::getIdodontologo();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
