inicio:
    path:     /inicio
    defaults: { _controller: AdministradorBundle:Default:inicio }
login:
    path:     /login
    defaults: { _controller: AdministradorBundle:Default:login }
logout:
    path:     /logout
    defaults: { _controller: AdministradorBundle:Default:logout }