plandetratamiento:
    path:     /
    defaults: { _controller: "ConnectionBDBundle:PlanDeTratamiento:index" }

plandetratamiento_show:
    path:     /{id}/show
    defaults: { _controller: "ConnectionBDBundle:PlanDeTratamiento:show" }

plandetratamiento_new:
    path:     /new
    defaults: { _controller: "ConnectionBDBundle:PlanDeTratamiento:new" }

plandetratamiento_create:
    path:     /create
    defaults: { _controller: "ConnectionBDBundle:PlanDeTratamiento:create" }
    requirements: { _method: post }

plandetratamiento_edit:
    path:     /{id}/edit
    defaults: { _controller: "ConnectionBDBundle:PlanDeTratamiento:edit" }

plandetratamiento_update:
    path:     /{id}/update
    defaults: { _controller: "ConnectionBDBundle:PlanDeTratamiento:update" }
    requirements: { _method: post|put }

plandetratamiento_delete:
    path:     /{id}/delete
    defaults: { _controller: "ConnectionBDBundle:PlanDeTratamiento:delete" }
    requirements: { _method: post|delete }
